---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: cluster-gitops
  namespace: acm-channels
spec:
  type: GitHub
  pathname: https://github.com/martineg/acm-policies.git