---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sb-boms
  namespace: acm-channels
  labels:
    subscription-pause: "false"
  annotations:
    apps.open-cluster-management.io/github-path: packages/boms
spec:
  channel: acm-channels/cluster-gitops
  placement:
    local: true
#  timewindow:
#    windowtype: "active"
#    location: "America/Los_Angeles"
#    daysofweek: [ "Friday", "Saturday", "Sunday" ]
#    hours:
#      - start: "05:00PM"
#        end: "10:00PM"
