---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pr-cluster-baseline
  namespace: acm-cluster-baseline
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
