---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: pb-sandbox
  namespace: acm-sandbox
placementRef:
  name: pr-sandbox
  namespace: acm-sandbox
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: pl-managed-cluster-info
  namespace: acm-sandbox
  kind: Policy
  apiGroup: policy.open-cluster-management.io
- name: pl-imagemanifestvuln
  namespace: acm-sandbox
  kind: Policy
  apiGroup: policy.open-cluster-management.io
