---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

# namespace: my-namespace
# namePrefix: dev-
# nameSuffix: "-001"
# commonLabels:
#   app: bingo

commonAnnotations:
    policy.open-cluster-management.io/standards: NIST 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
